version: '3.8'

services:
  bot:
    build: .
    env_file: telegram-bot/.env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: python telegram-bot/main.py

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
