services:
  prometheus:
    build:
      context: .
      dockerfile: prometheus.Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_provisioning_data:/etc/grafana/provisioning

volumes:
  prometheus_data: { }
  grafana_data: { }
  grafana_provisioning_data: { }
