app:
  api-token: "${API_TOKEN}"

spring:
  application:
    name: monidorm-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

#management:
#  server:
#    port: 8081
#
#  metrics:
#    tags:
#      application: ${spring.application.name}
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true
#
#  endpoint:
#    health:
#      enabled: true
#    prometheus:
#      enabled: true
#
#  endpoints:
#    web:
#      base-path: "/"
#      exposure:
#        include: "health,prometheus"
#      path-mapping:
#        "prometheus": "/metrics"
#
#  prometheus:
#    metrics:
#      export:
#        enabled: true
